site_name: Documentação do Site 

theme:
  font: 
    text: Arial
  palette:
    scheme: slate
    primary: deep orange
    accent: orange
  
  name: material
  features:
    - navigation.tabs
    - navigation.path
    - search.highlight
    - toc.integrate
 



